### ISSUE TITLE
Servers ping +380 ms

### ISSUE THREAD

**Issue by rabi31001** [Bluscream/GTACoop#23]
the china server is so laggy ! and the europe servers are locked with a password!!
then i decided to create my own server  all thing fine but when my friends join i got this : 
**(ERROR) SERVER: Can't handle tick: System.NullReferenceException: Object reference not set to an instance of an object.
at GTAServer.GameServer.Tick()**
is there any way to fix that problem or knew the european servers password ? 
master server is not working for me too the both master servers not working

 excuse my english ...

**Comment by rabi31001** [comment]
fixed that ... (you must create server from the f9 too beside the cmd server)
after friends login you can't ride a vehicle toghter , shared traffic make the game terrible and glicthy 
still so laggy even when ping 80ms
this project could have a great future if Bluscream care more about it.

**Comment by JohnHawkinsWei** [comment]
u can get in your friend's car by pressing G not F, but the wheel is not functional for the passager. 
even if i join my friend's server which in the same city, and the ping less than 10ms, we still have the same sync problem;(
